### ISSUE TITLE
Program bugs

### ISSUE THREAD

**Issue by dcoggin4963** [aptech/tspdlib#1]
'diff''   'myols'   '_get_lag'   'ADF_1break'  (and possibly others in you code)  are not defined in Gauss 19.  Please try and run your routines as currently written and then correct these issues.

**Comment by ec78** [comment]
Hello, thank you for your comment. 

The functions you mention are defined in the **tspdlib** library. If you are getting G0025 Undefined Errors related to these functions, it is possible that the **tspdlib** library did not install correctly. I suggest reviewing our [Using GAUSS Packages](https://www.aptech.com/blog/using-gauss-packages-complete-guide/) for more information on installing the library. 

One way to see if the library has installed correctly is to verify the files that are listed under the _tspdlib.lcg_  file in the **Library Tool** If you do not see files listed under the library, then the library has not loaded properly. 

![files_in_tspdlib](https://user-images.githubusercontent.com/10565435/66595723-2664b500-eb61-11e9-99fe-a72b0daccbd0.PNG)

If the files are listed, please let me know and we can troubleshoot further what is occurring.

**Comment by dcoggin4963** [comment]
Thanks for your reply. This has become much too frustrating for me. There
is no "Library Tool" in Gauss 19 under the Edit or View pages. I used the
Install Application utility under Tools to  install  *tspdlib* and  I still
get the errors I  noted. I will now  just use my usual unit root tests and
move on.

**Comment by ec78** [comment]
I am sorry to hear you are frustrated with this process. The most common error that users have with the **tspdlib** is caused by issues with installation. These errors usually occur because the wrong .zip file has been installed. Please make sure you are installing the **tspdlib_1.0.zip** located on the [**Release** page](https://github.com/aptech/tspdlib/releases) of this repository. 

The GAUSS **Library Tool** is a window that can be viewed from within the Edit window. 
![library_tool](https://user-images.githubusercontent.com/10565435/66609091-ccbeb380-eb7d-11e9-9551-82b00c540cd3.PNG)

You can locate the Library Tool using the tabs in the lower left hand of the  **Edit** window. 

If the **Library Tool** is not available, you may add it to the **Edit** view by navigating to **View>Library Tool**.

Finally, I would be more than happy to schedule an online virtual meeting with you to help troubleshoot the issue. If you would like to do this please let me know and we will arrange a convenient time offline. 

Best regards,
Erica

**Comment by jason-d-jones** [comment]
@dcoggin4963 You need to reinstall the TSPDLIB package. [This 30 second YouTube video shows you how to install a GAUSS package](https://www.youtube.com/watch?v=JxnfJRZEopg).

The package file you need to install is named `tspdlib_1.0.zip`. It can be [downloaded from this link](https://github.com/aptech/tspdlib/releases/download/v1.0.0/tspdlib_1.0.zip).

**Comment by dcoggin4963** [comment]
Thanks again for your reply. I was able to load and install the newer
version, tspdlib_1.0. As I noted earlier, the older version on github has
problems with installation. As for the programs, some run without
corrections, and some do not. I have not tested each one. I suggest the
author run each program on a sample datafile, make corrections, and then
post a new update that will run each program without editing and correcting.
Dan Coggin

**Comment by ec78** [comment]
Thank you for your suggestion. You will find that the procedures located in the source code have already been run on sample data in the example files located in the “pkgs/tspdlib/examples” folder located in your GAUSS home directory. Are you experiencing errors with these example files? If so, can you please provide the details of which file and what errors you are experiencing so we may appropriately solve this issues.

**Comment by dcoggin4963** [comment]
I will check out the examples folder and see of that helps.
